title: SAIO
email: arvid.kristoffersson@kodsport.se
description: >- 
  Den svenska AI-olympiaden 2025 är en tävling i artificiell intelligens för gymnasister i Sverige.
  Tävlingen har två delar: ett kval och en final. Kvalet kommer att hållas online och varar i en månad, 
  från 15 februari - 15 mars. Från kvalet blir de bästa inbjudna till en final i Göteborg i maj. 
  Där koras Sveriges bästa gymnasist i artificiell intelligens och lanslaget utses från de bästa fyra i finalen.
baseurl: "/"
url: "www.arvidkristoffersson.se"

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
