title: ArvidKristoffersson
email: arvid.kristoffersson@icloud.com
description: >- 
  Min hemsida
baseurl: "/site"
url: ""

theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
